backend:
  name: test-repo

media_folder: static/img
public_folder: /img

collections:
  - name: docs
    label: Docs
    folder: docs
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Sidebar Position, name: sidebar_position, widget: number, required: false }
      - { label: Body, name: body, widget: markdown }